### ISSUE TITLE
Upload field not working with Backpack v6 using new uploader

### ISSUE THREAD

**Issue by afagard** [Laravel-Backpack/PageManager#135]
# Bug report

### What I did:

PageTemplates.php

```
private function generic_page()
    {
        $this->crud->addField([
            'name' => 'hero_separator',
            'type' => 'custom_html',
            'value' => '<br><h3>Hero</h3><hr>',
        ]);
        $this->crud->addField([
            'name' => 'page_header',
            'label' => 'Hero Title',
            'type' => 'text',
            'fake' => true,
            'store_in' => 'extras'
        ]);
        $this->crud->addField([
            'name' => 'content',
            'label' => 'Hero Body',
            'type' => 'summernote'
        ]);
        \CRUD::field('hero_image')->type('upload')->fake(true)->store_in('extras')->withFiles();
```

### What I expected to happen:

That the `hero_image` field would populate in the extras column

### What happened:

The field attempted to populate a database column that did not exist: `hero_image`. `hero_image` was not placed in the `extras` array/json field. 

**SQLSTATE[42S22]: Column not found: 1054 Unknown column 'hero_image' in 'field list'**

### What I've already tried to fix it:

I wasn't sure how to fix this.

### Backpack, Laravel, PHP, DB version:

Backpack 6.0, Laravel 10.14.1, PHP 8.1.6

**Comment by pxpm** [comment]
Thanks for the report @afagard .

I've missed fake field usage in uploaders. I've now added support for them in https://github.com/Laravel-Backpack/CRUD/pull/5173

Cheers

**Comment by afagard** [comment]
@pxpm I am not sure if your update has solved the issue however (it might be still in progress). I manually updated the uploader from your commit and it still shows:

Field setup:

       ```
 \CRUD::field('hero_image')->type('upload')->fake(true)->store_in('extras')->withFiles([
            'fileNamer' => function (UploadedFile $file, $uploader) {
                $filename = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);
                return Str::slug($filename) . '-' . Str::random(10) . '.' . strtolower($file->getClientOriginalExtension());
            },
        ]);
```

Error: 

```
update
  `pages`
SET
  `extras` = "{\"page_header\":null,\"hero_content\":null,\"hero_image\":\"7-3nnALv6Ouv.png\",\"meta_title\":null,\"meta_description\":null,\"meta_keywords\":null}",
  `hero_image` = ?,
  `pages`.`updated_at` = 2023 -07 -04 01: 28: 42
WHERE
  `id` = 3
```

As you can see, the extras now has the file populated, but it is till trying to populate the `hero_image` field. I could be missing something.

**Comment by pxpm** [comment]
Hey @afagard thanks for the review. 

Indeed, it was missing some checking when updating. 

I've pushed some code that from my tests fixes the problem you mentioned. 

If you want to give it a try, let me know how it goes 🙏 

Thanks again 💪

**Comment by afagard** [comment]
@pxpm Unfortunately it has not, I ran composer update to get the newest version that you just committed. And what I said in my immediately previous comment is still what is happening. I am not sure if you read it in its entirety as there might be some useful hints(?) towards the end.

It could also be a "me" issue*, I've simplified my code in to something that should be reproducible for you:

```
<?php

namespace App;

use Illuminate\Http\UploadedFile;
use Illuminate\Support\Str;

trait PageTemplates
{
    private function generic_page(): void
    {
        \CRUD::field('hero_image')
            ->hint('This field is really only meant for site administrators who know the design implications')
            ->type('upload')->fake(true)->store_in('extras')->withFiles([
                'fileNamer' => function (UploadedFile $file, $uploader) {
                    return Str::random(10) . '.' . strtolower($file->getClientOriginalExtension());
                    //$filename = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);
                    //return safeFilename($filename) . '-' . Str::random(10) . '.' . strtolower($file->getClientOriginalExtension());
                },
            ]);
    }
}
```

Yields:

**SQLSTATE[42S22]: Column not found: 1054 Unknown column 'hero_image' in 'field list'**

```
update
  `pages`
SET
  `extras` = { "hero_image": { } },
  `hero_image` = zp9zkQFu5Y.png,
  `pages`.`updated_at` = 2023 -07 -05 05: 33: 43
WHERE
  `id` = 3
```

* Am I constructing the `\CRUD::field('hero_image')` correctly??

**Comment by tabacitu** [comment]
Heads-up @afagard , yesterday Pedro's fix was _merged_, but not _released_. When you did `composer update` you probably didn't get the fix. I've just [tagged CRUD 6.0.1](https://github.com/Laravel-Backpack/CRUD/releases/tag/6.0.1) so now after a `composer update` you should get it.

(I'm not saying it's totally fixed - I haven't tested this, I'll let Pedro do his thing; but just thinking the tag might help)

**Comment by afagard** [comment]
Indeed, I thought it was released. I just did a composer update to get 6.0.1. I am still experiencing issues but I suppose you all are still working on it 👍 

Tag me if you want me to test any of it - I can be the guinea pig.

**Comment by afagard** [comment]
@pxpm Hey Pedro, I just pulled it, and when I go to the page where the field is I immediately get a

**Undefined array key "hero_image"**

See: [https://flareapp.io/share/dmk8yxAP](https://flareapp.io/share/dmk8yxAP)

Please note, the `extras` column is null in the db for this current page

**Comment by afagard** [comment]
@pxpm Working good for me! I think you nailed it 🚀
